sudo: false

language: node
node_js:
  - "6"

cache:
  directories:
    - node_modules

before_install:
  - rvm install 2.3.0
  - bundle install
  - npm install -g gulp-cli
  - ./scripts/setup-prod.sh
